### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Review by cs-googler — COMMENTED** [review]
Hi, thanks for the commit! We will update it internally and sync the change to github.

**Review by HTML-CODDER — COMMENTED** [review]
Please I want to know if it's ok for me to adopt this libraries?

**Review by HTML-CODDER — COMMENTED** [review]
Update libraries #156

**Comment by hannesa2** [comment]
This pull request is closed. 
When you want a fork with all libraries updates and all samples merged to on demo app you will find it here https://github.com/hannesa2/mlkit

**Pull request closed without merging**
