### PR TITLE
fix: fix a typo

### PR DESCRIPTION
**Pull request by pentiumao**
Should use setPerformanceMode instead of setClassificationMode

### CODE REVIEW

**Comment by pentiumao** [comment]
@googlebot I signed it!

**Comment by calren** [comment]
@pentiumao Thanks for the fix! Can we also fix the same issue in `[FaceDetectionActivity.java](https://github.com/googlesamples/mlkit/blob/master/android/android-snippets/app/src/main/java/com/google/example/mlkit/FaceDetectionActivity.java#L49)`?

**Comment by pentiumao** [comment]
@calren Sure, sorry for the file missed.

**Review by cs-googler — APPROVED** [review]

**Comment by zhouyiself** [comment]
Thanks for the pull request!
Due to how this repo works, we will need do the fix internally and sync it out in the next release.

**Pull request merged**
